//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionMaterialsManagement
{

    public partial class OrderHistory
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.GridView gvMyOrders;

        protected global::System.Web.UI.WebControls.Panel pnlDetails;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblDetailsTitle;

        protected global::System.Web.UI.WebControls.GridView gvOrderItems;

        protected global::System.Web.UI.WebControls.Button btnCloseDetails;
    }
}
